# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Teest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Teest


pod 'ShalHiDone', :path => "../ShalHiDone"
#pod 'ShalHiDone', :git => "https://github.com/ShalHi66/ShalHiDone.git", :tag => "1.0.0"



end


post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end